host:
  url: 192.168.0.11
server:
  port: 30011
spring:
  activemq:
    in-memory: true
    pool:
      enabled: false
    broker-url: tcp://${host.url}:61616
    user: admin
    password: a1234567@!
    pooled: false
  freemarker:
    template-loader-path: classpath:/templates/
  mvc:
    static-path-pattern: classpath:/static/
  application:
    name: his-jms
logging:
  level: INFO
  file: G:/logger.log
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://${host.url}:30002/eureka/
